# Generated by Django 6.0.6 on 2026-06-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signalappel',
            new_name='appels_sign_destina_0b47a4_idx',
            old_name='appels_sign_destina_e40f65_idx',
        ),
        migrations.RenameIndex(
            model_name='signalappel',
            new_name='appels_sign_appel_i_0a74b4_idx',
            old_name='appels_sign_appel_i_ee4d09_idx',
        ),
    ]
