# Generated by Django 6.0.6 on 2026-06-09 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('auteur_nom', models.CharField(max_length=200)),
                ('encadreur', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('DIPET1', 'DIPET I (Niveau 3)'), ('DIPET2', 'DIPET II (Niveau 5)')], max_length=10)),
                ('annee_academique', models.CharField(max_length=9)),
                ('resume', models.TextField()),
                ('mots_cles', models.CharField(blank=True, max_length=500)),
                ('fichier_pdf', models.FileField(upload_to='memoires/')),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('VALIDE', 'Archivé'), ('REJETE', 'Rejeté')], default='SOUMIS', max_length=10)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('nb_telechargements', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depose_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires_deposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mémoire',
                'verbose_name_plural': 'Mémoires',
                'ordering': ['-annee_academique', 'titre'],
            },
        ),
    ]
