# Generated by Django 6.0.6 on 2026-06-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0002_statut_prevalide'),
        ('memoires', '0003_article_ieee_images'),
    ]

    operations = [
    ]
