# Generated by Django 6.0.6 on 2026-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0004_merge_0002_statut_prevalide_0003_article_ieee_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='resume',
            field=models.TextField(verbose_name='Abstract'),
        ),
    ]
