# Generated by Django 6.0.6 on 2026-06-09 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('type_doc', models.CharField(choices=[('COURS', 'Cours'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EXAMEN', 'Examen'), ('CORRIGE', 'Corrigé'), ('SUPPORT', 'Support pédagogique'), ('ADMIN', 'Note administrative')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('departement', models.CharField(max_length=100)),
                ('filiere', models.CharField(blank=True, max_length=100)),
                ('niveau', models.IntegerField(blank=True, null=True)),
                ('annee_academique', models.CharField(blank=True, max_length=9)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('nb_telechargements', models.IntegerField(default=0)),
                ('nb_consultations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
